### ISSUE TITLE
Congrats

### ISSUE THREAD

**Issue by yazansosyolog** [zehrakuru/Cinemate#1]
Çok tatlı bir uygulama olmuş ellerine sağlık. Pdf de çok iyi bu arada. Pdf'in tasarımını ne ile yaptın?

**Comment by zehrakuru** [comment]
Çok teşekkürler, beğenmenize çok sevindim.
https://create.microsoft.com/en-us/powerpoint-templates sitesinden template seçerek ppt olarak hazırladım pdf'i
